# Generated by Django 5.2.2 on 2025-07-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_contributor_book_bookcontributor_book_contributors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcontributor',
            old_name='contributors',
            new_name='contributor',
        ),
    ]
